dataset_name: mnist
datasets: !include_from ./${dataset_name}.yml

train_loader: !@torch.utils.data.DataLoader
  dataset: ${datasets.train_dataset}
  batch_size: 64
  shuffle: true

val_loader: !@torch.utils.data.DataLoader
  dataset: ${datasets.val_dataset}
  batch_size: 64
  shuffle: false
