# Run with: PYTHONPATH=. python -m pyamlo main.yml

# Include data and model configurations
dataset: mnist
model_name: mobilenet

model: !include_from ${model_name}.yml
datasets: !include_from ${dataset}.yml

# DataLoaders
train_loader: !@torch.utils.data.DataLoader
  dataset: ${datasets.train_dataset}
  batch_size: 64
  shuffle: true

val_loader: !@torch.utils.data.DataLoader
  dataset: ${datasets.val_dataset}
  batch_size: 64
  shuffle: false

lightning_model: !@simple_cnn.LightningModel
  model: ${model}
  lr: 0.001

# Trainer
trainer: !@lightning.pytorch.Trainer
  max_epochs: 1
  accelerator: "auto"
  devices: 1

# Start training directly from config!
train: !@$trainer.fit
  model: ${lightning_model}
  train_dataloaders: ${train_loader}
  val_dataloaders: ${val_loader}
