dataset_name: mnist
model_name: cnn
optimizer_name: adam
batch_size: 32
epochs: 1
validation_split: 0.1

dataset: !include_from datasets/${dataset_name}.yml

pooling: MaxPooling2D
model: !include_from models/${model_name}.yml

compile_step: !$@model.compile
  optimizer: ${optimizer_name}
  loss: "sparse_categorical_crossentropy"
  metrics: ["accuracy"]

summary_step: !$@model.summary

# Train the model
history: !$@model.fit
  x: ${dataset.x_train}
  y: ${dataset.y_train}
  batch_size: ${batch_size}
  epochs: ${epochs}
  validation_split: ${validation_split}
  verbose: 1

# Evaluate on test set
test_results: !$@model.evaluate
  x: ${dataset.x_test}
  y: ${dataset.y_test}
  verbose: 1

print_results: !@print "Test results: ${test_results}"
final_message: !@print "Training completed!"
