# include data and model configurations
include!:
  - ./devices/auto.yml 
  - ./datasets/selector.yml
  - ./models/selector.yml
  - ./trainers/selector.yml
  - ./evaluators/selector.yml

model_msg: !@print Model:\n ${model}

# Start training for 1 epoch
epochs: 1
train_result: !@$trainer.run
  data: ${train_loader}
  max_epochs: ${epochs}

# Run evaluation
eval_result: !@$evaluator.run
  data: ${val_loader}

results_msg: !@pprint.pprint ${evaluator.state.metrics}